name: LifesPluginS3
author: trololo11
version: '${project.version}'
main: me.trololo11.lifespluginseason3.LifesPlugin
api-version: '1.20'
commands:
  getitems:
    description: "Gets all your items :D"
  setlifes:
    description: "Sets player's amount of lifes"
  takelife:
    description: "Takes your life!"
    aliases:
      - "kys"
  lifesmenu:
    description: "Opens the main lifes menu"
  setprogress:
    description: "Sets a quest progress!"
  getallcards:
    description: "Gives you all the cards lol"
  isinvfull:
    description: "IS inv full?"
  ping:
    description: "Get your ping!"
  getcard:
    description: "Gets yours card"
permissions:
  3lifes3.admin:
    description: "A administator perm for the 3LifesPluginSeason3"