name: LifesPluginS3
version: '${project.version}'
main: me.trololo11.lifespluginseason3.LifesPlugin
api-version: '1.20'
commands:
  getitems:
    description: "Gets all your items :D"
  setlifes:
    description: "Sets player's amount of lifes"
  takelife:
    description: "Takes your life!"
  lifesmenu:
    description: "Opens the main lifes menu"
permissions:
  3lifes3.admin:
    description: "A administator perm for the 3LifesPluginSeason3"