name: LifesPluginS3
author: trololo11
version: '${project.version}'
main: me.trololo11.lifespluginseason3.LifesPlugin
api-version: '1.20'
commands:
  setlifes:
    description: "Sets player's amount of lifes"
  takelife:
    description: "Takes your life!"
    aliases:
      - "kys"
  lifesmenu:
    description: "Opens the main lifes menu"
  setprogress:
    description: "Sets a quest progress!"
  ping:
    description: "Get your ping!"
  getcard:
    description: "Gets yours weekly random card"
  startserver:
    description: "Starts the server lol"
permissions:
  3lifes3.admin:
    description: "A administator perm for the 3LifesPluginSeason3"
  3lifes3.stats:
    description: "A perm that allows you to see the stats of quests in 3LifesPluginS3"